---
title: "Miscellaneous `ggplot` Tips"
date: 'Last compiled: `r format(Sys.time(), "%A, %B %d, %Y - %X.")`'
author: 'Alan T. Arnholt'
output: 
    bookdown::html_document2
---

```{r label = "setup", include = FALSE, message = FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", warning = FALSE, message = FALSE)
```

# Changing Shape and Color

```{r}
library(PASWR2)
library(ggplot2)
ggplot(data = BODYFAT, aes(x = age, y = fat, shape = sex, color = sex)) +
  geom_point(size = 6) +
  scale_shape_manual(values = c(F = "\u2640", M = "\u2642")) + 
  scale_color_manual(values = c("purple", "darkgreen")) +
  labs(x = "Age", y = "Percent Body Fat") +
  theme_bw() + 
  ggtitle(label = "Black and White Theme", subtitle = "Source: Mazess, R. B., Peppler, W. W., and Gibbons, M. (1984) Total Body \nComposition by Dual-Photon (153 Gd) Absorptiometry. American Journal \nof Clinical Nutrition, 40, 4: 834-839.")
```

# No Grid Lines

```{r}
ggplot(data = BODYFAT, aes(x = age, y = fat, shape = sex, color = sex)) +
  geom_point(size = 6) +
  scale_shape_manual(values = c(F = "\u2640", M = "\u2642")) + 
  scale_color_manual(values = c("purple", "darkgreen")) +
  theme(
    axis.text = element_text(size = 14),
    legend.key = element_blank(),
    legend.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(fill = NA, color = "grey20")
  ) +
  labs(x = "Age", y = "Percent Body Fat") +
  ggtitle(label = "No Grid Lines", subtitle = "Source: Mazess, R. B., Peppler, W. W., and Gibbons, M. (1984) Total Body \nComposition by Dual-Photon (153 Gd) Absorptiometry. American Journal \nof Clinical Nutrition, 40, 4: 834-839.")
```

# An Ugly Theme

```{r}
ggplot(data = BODYFAT, aes(x = age, y = fat, shape = sex, color = sex)) +
  geom_point(size = 6) +
  scale_shape_manual(values = c(F = "\u2640", M = "\u2642")) + 
  scale_color_manual(values = c("purple", "darkgreen")) +
  theme(
    axis.text = element_text(size = 14),
    legend.key = element_rect(fill = "white"),
    legend.background = element_rect(fill = "pink"),
    panel.grid.major = element_line(color = "white"),
    panel.grid.minor = element_line(color = "white"),
    panel.background = element_rect(fill = "lightcyan")
  ) +
  labs(x = "Age", y = "Percent Body Fat") +
  ggtitle(label = "Customized (Ugly) Theme", subtitle = "Source: Mazess, R. B., Peppler, W. W., and Gibbons, M. (1984) Total Body \nComposition by Dual-Photon (153 Gd) Absorptiometry. American Journal \nof Clinical Nutrition, 40, 4: 834-839.")
```

For more information on themes, read the ggplot2 theme [vignette](http://docs.ggplot2.org/dev/vignettes/themes.html).